### ISSUE TITLE
What's the point of transparent outlines?

### ISSUE THREAD

**Issue by cvrebert** [tachyons-css/tachyons-outlines#1]
Pardon my lack of imagination, but how are transparent outlines useful exactly? Aren't they indistinguishable from `outline: 0;`?

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
